#!/usr/bin/env pwsh
<#
.SYNOPSIS
    Validates GitHub secrets and variables required for the Contoso Resilience Demo.

.DESCRIPTION
    This script checks if all required GitHub secrets and variables are configured
    for the CI/CD pipelines to work properly.

.EXAMPLE
    ./scripts/validate-secrets.ps1
#>

param(
    [string]$Repository
)

# Colors for output
function Write-Success { param($Message) Write-Host "✅ $Message" -ForegroundColor Green }
function Write-Warning { param($Message) Write-Host "⚠️  $Message" -ForegroundColor Yellow }
function Write-Error { param($Message) Write-Host "❌ $Message" -ForegroundColor Red }
function Write-Info { param($Message) Write-Host "ℹ️  $Message" -ForegroundColor Cyan }

Write-Host ""
Write-Host "🔐 GitHub Secrets & Variables Validator" -ForegroundColor Magenta
Write-Host "========================================" -ForegroundColor Magenta
Write-Host ""

# Auto-detect repository from git remote
if (-not $Repository) {
    try {
        $remoteUrl = git remote get-url origin 2>$null
        if ($remoteUrl -match 'github\.com[:/](.+?)(?:\.git)?$') {
            $Repository = $Matches[1]
        }
    }
    catch {
        # Ignore errors
    }
}

if (-not $Repository) {
    Write-Error "Could not detect repository. Please specify with -Repository owner/repo"
    exit 1
}

Write-Info "Repository: $Repository"
Write-Host ""

# Check if gh CLI is available
if (-not (Get-Command gh -ErrorAction SilentlyContinue)) {
    Write-Error "GitHub CLI (gh) is not installed or not in PATH"
    Write-Host "Install from: https://cli.github.com/"
    exit 1
}

# Check if authenticated
$authStatus = gh auth status 2>&1
if ($LASTEXITCODE -ne 0) {
    Write-Error "Not authenticated with GitHub CLI"
    Write-Host "Run: gh auth login"
    exit 1
}

Write-Host "📋 Checking Required Secrets..." -ForegroundColor Cyan
Write-Host ""

# Required secrets for all workflows
$requiredSecrets = @(
    @{ Name = "AZURE_CLIENT_ID"; Description = "Azure Service Principal Client ID (for OIDC)" },
    @{ Name = "AZURE_TENANT_ID"; Description = "Azure AD Tenant ID" },
    @{ Name = "AZURE_SUBSCRIPTION_ID"; Description = "Azure Subscription ID" },
    @{ Name = "AZURE_SQL_ADMIN_PASSWORD"; Description = "SQL Server admin password" },
    @{ Name = "AZURE_SQL_APP_USER_PASSWORD"; Description = "SQL app user password for applications" }
)

# Optional secrets
$optionalSecrets = @(
    @{ Name = "AZURE_CREDENTIALS"; Description = "Service Principal JSON (fallback for non-OIDC)" },
    @{ Name = "GH_PAT"; Description = "GitHub PAT with 'repo' scope (for auto-setting variables)" }
)

# Required variables
$requiredVariables = @(
    @{ Name = "AZURE_ENVIRONMENT_NAME"; Description = "Unique environment name prefix (e.g., cntso-demo)" },
    @{ Name = "AZURE_LOCATION"; Description = "Azure region (e.g., westus2)" }
)

# Auto-generated variables (set by infrastructure workflow)
$autoGeneratedVariables = @(
    @{ Name = "AZURE_RESOURCE_GROUP"; Description = "Resource group name (auto-set by infrastructure)" },
    @{ Name = "AZURE_WEBAPP_NAME"; Description = "Web app name (auto-set by infrastructure)" },
    @{ Name = "AZURE_API_NAME"; Description = "API app name (auto-set by infrastructure)" },
    @{ Name = "AZURE_LOAD_TEST_RESOURCE"; Description = "Load test resource name (auto-set by infrastructure)" },
    @{ Name = "AZURE_WEBAPP_URL"; Description = "Web app URL (auto-set by infrastructure)" },
    @{ Name = "AZURE_API_URL"; Description = "API URL (auto-set by infrastructure)" },
    @{ Name = "AZURE_KEY_VAULT_NAME"; Description = "Key Vault name (auto-set by infrastructure)" },
    @{ Name = "AZURE_KEY_VAULT_ENDPOINT"; Description = "Key Vault endpoint URL (auto-set by infrastructure)" }
)

# Get existing secrets
$existingSecrets = @()
try {
    $secretsList = gh secret list --repo $Repository 2>&1
    if ($LASTEXITCODE -eq 0) {
        $existingSecrets = $secretsList | ForEach-Object { ($_ -split '\t')[0] }
    }
}
catch {
    Write-Warning "Could not retrieve secrets list"
}

# Get existing variables
$existingVariables = @()
try {
    $variablesList = gh variable list --repo $Repository 2>&1
    if ($LASTEXITCODE -eq 0) {
        $existingVariables = $variablesList | ForEach-Object { ($_ -split '\t')[0] }
    }
}
catch {
    Write-Warning "Could not retrieve variables list"
}

$missingSecrets = @()
$missingVariables = @()

# Check required secrets
Write-Host "Required Secrets:" -ForegroundColor White
foreach ($secret in $requiredSecrets) {
    if ($existingSecrets -contains $secret.Name) {
        Write-Success "$($secret.Name)"
    }
    else {
        Write-Error "$($secret.Name) - MISSING"
        $missingSecrets += $secret
    }
}

Write-Host ""
Write-Host "Optional Secrets:" -ForegroundColor White
foreach ($secret in $optionalSecrets) {
    if ($existingSecrets -contains $secret.Name) {
        Write-Success "$($secret.Name)"
    }
    else {
        Write-Warning "$($secret.Name) - Not set (optional)"
    }
}

Write-Host ""
Write-Host "📋 Checking Required Variables..." -ForegroundColor Cyan
Write-Host ""

Write-Host "Required Variables:" -ForegroundColor White
foreach ($variable in $requiredVariables) {
    if ($existingVariables -contains $variable.Name) {
        Write-Success "$($variable.Name)"
    }
    else {
        Write-Error "$($variable.Name) - MISSING"
        $missingVariables += $variable
    }
}

Write-Host ""
Write-Host "Auto-Generated Variables (set by infrastructure workflow):" -ForegroundColor White
foreach ($variable in $autoGeneratedVariables) {
    if ($existingVariables -contains $variable.Name) {
        Write-Success "$($variable.Name)"
    }
    else {
        Write-Warning "$($variable.Name) - Not set yet (will be auto-generated)"
    }
}

Write-Host ""
Write-Host "========================================" -ForegroundColor Magenta
Write-Host ""

# Summary and commands to fix
if ($missingSecrets.Count -gt 0 -or $missingVariables.Count -gt 0) {
    Write-Host "🔧 Commands to set missing items:" -ForegroundColor Yellow
    Write-Host ""
    
    foreach ($secret in $missingSecrets) {
        Write-Host "# $($secret.Description)" -ForegroundColor DarkGray
        Write-Host "gh secret set $($secret.Name) --repo $Repository" -ForegroundColor White
        Write-Host ""
    }
    
    foreach ($variable in $missingVariables) {
        Write-Host "# $($variable.Description)" -ForegroundColor DarkGray
        Write-Host "gh variable set $($variable.Name) --body `"<value>`" --repo $Repository" -ForegroundColor White
        Write-Host ""
    }
    
    Write-Host "========================================" -ForegroundColor Magenta
    Write-Host ""
    Write-Error "Missing required secrets/variables. Please configure them before running pipelines."
    exit 1
}
else {
    Write-Success "All required secrets and variables are configured!"
    Write-Host ""
    
    # Check for auto-generated variables
    $missingAutoVars = $autoGeneratedVariables | Where-Object { $existingVariables -notcontains $_.Name }
    if ($missingAutoVars.Count -gt 0) {
        Write-Info "Note: Some auto-generated variables are not set yet."
        Write-Info "Run the infrastructure workflow first to populate them automatically."
        Write-Host ""
        Write-Info "Or set them manually with a GH_PAT secret (GitHub PAT with 'repo' scope)."
    }
    
    exit 0
}
